Добавить возможность оставлять отзывы на фильм
Omorlan/java-filmorate pull request #12
Opened 2024-07-18 22:27 UTC by Omorlan

feat: Добавить две таблицы reviews и review_likes 
feat: добавить возможность оставлять отзывы на фильм
fix: Исправить путаницу в ErrorHandler
fix: Добавить .properties

2024-07-19 19:04 UTC, Paul-Value requested changes
В целом все хорошо, написал несколько рекомендаций

2024-07-19 19:07 UTC, Gadetych approved these changes
Предложил улучшения, если будет время. А так-то хорошо)

2024-07-19 19:07 UTC, Gadetych commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewStorageDb.java
> +                """;
попробуй так:
UPDATE reviews SET useful = useful +1
WHERE review_id =?

2024-07-20 10:31 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewStorageDb.java
> +public class ReviewStorageDb implements ReviewStorage {
Согласен, поправил

2024-07-20 10:43 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/service/ReviewService.java
> +    }
блага цивилизации

2024-07-20 10:45 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewStorageDb.java
> +        return jdbcTemplate.query("SELECT * FROM reviews", new ReviewMapper());
Я переделал так же как в остальных классах, пусть не выделяется

2024-07-21 11:48 UTC, Paul-Value approved these changes
Все хорошо)

2024-07-21 11:49 UTC, Paul-Value approved these changes

2024-07-22 12:46 UTC, merged