Реализовать вывод общих с другом фильмов с сортировкой по их популярности.
Omorlan/java-filmorate pull request #13
Opened 2024-07-19 10:44 UTC by Gadetych

2024-07-19 11:13 UTC, Omorlan requested changes
Поправить вайлдкард в остальном всё хорошо

2024-07-19 11:13 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
import org.springframework.web.bind.annotation.*;
Wildcard плохая практика, лучше его избегать

2024-07-19 19:22 UTC, Paul-Value reviewed
Замечаний нет)

2024-07-20 13:52 UTC, Omorlan approved these changes

2024-07-20 14:09 UTC, Omorlan approved these changes

2024-07-20 17:07 UTC, merged