Develop
Omorlan/java-filmorate pull request #22
Opened 2024-07-24 17:04 UTC by Paul-Value

Групповой проект

2024-07-26 20:15 UTC, afomkina requested changes
Не хватает описания того, какие задания были выполнены. Нужно добавить в описание пулл реквеста или в файл README

2024-07-26 20:15 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/event/Event.java
> +public class Event {
Не хватает модификаторов доступа у полей класса

2024-07-26 20:15 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewStorageDb.java
> +        return jdbcTemplate.queryForObject(sqlQuery, Boolean.class, reviewId);
`queryForObject` возвращает `null`, если запрос не возвращает результатов. Когда `null` попытается преобразоваться в примитивный тип `boolean` , это вызывает исключение `NullPointerException`. Стоит добавить проверку на `null`, прежде чем возвращать значение

2024-07-26 20:15 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorageDb.java
> +                                  WHERE user_id IN (SELECT user2_id
Нужно избавиться от вложенных подзапросов

2024-07-26 20:15 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2024-07-27 10:49 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/model/event/Event.java
> +public class Event {
Добавили

2024-07-27 10:50 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/storage/review/ReviewStorageDb.java
> +        return jdbcTemplate.queryForObject(sqlQuery, Boolean.class, reviewId);
Добавили проверку

2024-07-27 10:50 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorageDb.java
> +                                  WHERE user_id IN (SELECT user2_id
сократили

2024-07-27 11:44 UTC, afomkina approved these changes
Вы проделали большую работу! У вас получился отличный проект и появились навыки работы в команде. Вы хорошо разобрались во взаимодействие между слоями сервис-контроллер-репозиторий.  У вас получились отличные запросы к таблицам.
Молодцы, что сделали все фичи!

2024-08-04 12:02 UTC, merged