Выполнить тз 10 спринта
Omorlan/java-filmorate pull request #5
Opened 2024-04-11 13:15 UTC by Omorlan

feat: Добавить контроллеры пользователя и фильмов
feat: Добавить тесты

2024-04-11 14:05 UTC, Omorlan commented
Привет, автотесты гита валятся на static модификаторе фабричных методов для параметризированных тесто, что с этим делать кроме как убирать параметризированные тесты я не знаю, поэтому решил оставить так, потому что все вроде 
работает

2024-04-11 14:09 UTC, Omorlan commented
Туда же, изначально не пропускало с 21 версией, вернул как в родном проекте 11, а 11 версия ругается на static, но мы же давно должны были к 21 перейти

2024-04-12 13:59 UTC, afomkina requested changes

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(MIN_DATE)) {
Можно реализовать кастомную аннотацию валидации, чтобы полностью отказаться от ручной валидации.
Вот [отличная статья](https://reflectoring.io/bean-validation-with-spring-boot/#a-custom-validator-with-spring-boot:~:text=to%20none.-,A%20Custom%20Validator%20with%20Spring%20Boot,-If%20the%20available), в которой подробно описано, как это можно сделать

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            if (updatedUser.getId() == null) {
Лучше валидировать спингом [@NotNull](https://reflectoring.io/bean-validation-with-spring-boot/#:~:text=%40-,NotNull,-%3A%20to%20say)

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getDescription().length() > MAX_DESC_LENGTH) {
Не нужно писать код самостоятельно, когда фреймворк это может делать за нас. Проще использовать одну аннотацию, а не писать несколько строк кода:
[@Size](https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/javax/validation/constraints/Size.html)

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            if (updatedFilm.getId() == null) {
Используй аннотацию валидации

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } catch (Exception exception) {
Нужно отлавливать конкретное исключение /  несколько определенных исключений, которые могут возникнуть в ходе работы программы, а не самое абстрактное

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Collection<User> findAll() {
Используй менее абстрактный интерфейс

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            userValidation(user);
Попробуй избавиться от метода и оставить только валидацию через аннотации

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } catch (ConditionsNotMetException | DataFormatException | DuplicatedDataException exception) {
🔥

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>  public class Film {
У всех полей класса должны быть модификаторы доступа

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
У всех полей класса должны быть модификаторы доступа

2024-04-12 13:59 UTC, afomkina commented on src/main/java/ru/yandex/practicum/filmorate/util/HttpStatusCode.java
> +public enum HttpStatusCode {
У спринга есть уже готовый класс с перечислением кодов ответа: [HttpStatus](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/HttpStatus.html)

2024-04-12 13:59 UTC, afomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
FYI Для тестирования спринговой валидации можно воспользоваться [валидатором](https://stackoverflow.com/questions/29069956/how-to-test-validation-annotations-of-a-class-using-junit)

2024-04-13 12:38 UTC, Omorlan commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +class FilmControllerTest {
Спасибо интереса ради переписал тесты

2024-04-13 12:38 UTC, Omorlan commented on src/main/java/ru/yandex/practicum/filmorate/util/HttpStatusCode.java
> +public enum HttpStatusCode {
Да так удобнее, такое тоже попробовал перед тем как тесты переделать

2024-04-14 10:38 UTC, afomkina approved these changes

2024-04-14 10:48 UTC, merged